### PR TITLE
Upgrade to one-true-path-experiment 6.0.0

### LINKED ISSUE #110: Upgrade to new one-true-path-experiment major version
Hello Jakub,
@folkertdev just released a [new version](https://github.com/folkertdev/one-true-path-experiment/compare/5.0.2...6.0.0) of one-true-path-experiment, with fixes for path and floating number coordinates parsing. Unfortunately the path parser fix imply a major version bump for it, so elm-visualization can't match it. Would you mind bumping this version dep? (I can make a PR to prepare this).
Have a nice day,
Emilien

### PR DESCRIPTION
**Pull request by etaque**
Fix #110. Close #112.

* Minor deps bumps cascaded from one-true-path-experiment upgrade 
* I had to explicitly import helpers in test, don't know why it wasn't needed before though.

### CODE REVIEW

**Comment by gampleman** [comment]
Can you comment on the merits of this vs https://github.com/gampleman/elm-visualization/pull/112? Personally I would expect the dependency ranges to widen if there are no breaking changes?

**Comment by etaque** [comment]
Yes, that's strange but #112 fails to meet deps constraints for me when running `elm-test`:

```
-- INCOMPATIBLE DEPENDENCIES ------------------------------------------ elm.json

The dependencies in your elm.json are not compatible.

Did you change them by hand? Try to change it back! It is much more reliable to
add dependencies with elm install or the dependency management tool in
elm reactor.
```

**Comment by etaque** [comment]
And widening to `"6.0.0 <= v < 7.0.0"` on my branch leads to same error. But even more strange, running `elm-test` on `master` also fails with the same. Do you have it passing?

**Comment by etaque** [comment]
Precision: from those three branches, `elm make` works fine. It's only the tests that are causing problems.

**Comment by gampleman** [comment]
Yeah something strange seems to be happening with the tests. I'll try to investigate, but I'm a bit busy this week.

**Comment by gampleman** [comment]
@etaque at least locally upgrading to elm-test rev6 seems to have solved this problem, so I've widened the ranges again. Hope this works for you.

**Comment by etaque** [comment]
Yes, all good! :+1:

**Pull request merged**
