### PR TITLE
 Fixes float tests numerical stability issues (#73) 

### PR DESCRIPTION
**Pull request by Anton-4**
- Used Expect.within to prevent problems with previous rounding approach.
- I ran all tests 40 times so I expect all problems to be resolved.

### CODE REVIEW

**Comment by gampleman** [comment]
Hi @Anton-4, thanks a lot for this! I've pushed a commit which should fix failures I've seen with some of the new color code: colours are generally 8bit, which is the precision the algorithms work with and colours will drift if much higher precision is used, so I think the newer test is fine.

I'm still seeing crashes in `Scale.LinearTests`:

```
↓ Scale.LinearTests
↓ Scale.linear
✗ invert is the inverse of convert

    This test failed because it threw an exception: "RangeError: Maximum call stack size exceeded"
```

This can be reproduced with:

```
elm-test --fuzz 10000 --seed 151568178007981 /Users/gampleman/Programming/elm-visualization/tests/Scale/LinearTests.elm
```

**Comment by Anton-4** [comment]
Interesting, I think the default fuzz is significantly lower, which is why I may have missed it.
I will take a look at it this week!

**Comment by Anton-4** [comment]
What I think happened is that the test failed and the `RangeError` occurred when elm-test was trying to retrieve the values that caused the failure. I lowered the precision to 0.01 for that test. Due to the number of operations required for the combination of convert and invert there can be a significant loss of precision when using combinations of very large and very small numbers.

**Comment by gampleman** [comment]
Sorry I am rather ill at the moment, so It will take me some time to have a look. Thanks again for taking a look at this.

**Comment by Anton-4** [comment]
Oh yeah no problem, take care!

**Comment by gampleman** [comment]
Thanks again @Anton-4, this is greatly appreciated!

**Pull request merged**
